spec-version: 0.30.0
name: co-optics
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
  - { name: "base", version: ">=4.13 && <4.14" }
  - profunctors
  - bifunctors
  - containers
  - transformers
  - mtl
  - digit
  - QuickCheck
  - hedgehog
  - lens
  - generic-lens
  - generics-sop

  - monoidal

ghc-options: [-Wall, -fconstraint-solver-iterations=20]
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes
  - QuantifiedConstraints

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses
  - TypeFamilies
  - FunctionalDependencies

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures

  - TupleSections

  - PackageImports

library: {}
executable:
  main: Main.hs
