spec-version: 0.30.0
name: co-optics
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: ">=4.13 && <4.14" }

ghc-options: [-Wall, -fconstraint-solver-iterations=20]
default-extensions:
- GADTs

- StandaloneDeriving
- DeriveFunctor
- DerivingVia
- GeneralizedNewtypeDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses
- TypeFamilies
- FunctionalDependencies

- ConstraintKinds
- DataKinds
- PolyKinds
- KindSignatures

- UndecidableInstances
- FlexibleInstances
- FlexibleContexts
- DefaultSignatures

- TupleSections

- PackageImports

library:
  source-dirs: src
  dependencies:
  - profunctors
  - bifunctors
  - containers
  - transformers
  - mtl
  - digit
  - QuickCheck
  - hedgehog
  - lens
  - generic-lens
  - generics-sop
  - monoidal

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - co-optics
